<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\modules\pagomiscuentas\models\PagomiscuentasFile;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model \app\modules\pagomiscuentas\models\PagomiscuentasFile */

$this->title = Yii::t('pagomiscuentas', 'Import of {name} of {date}', ['name'=>$model->company->name, 'date'=>$model->date]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('pagomiscuentas', 'PagoMisCuentas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="partner-view">
    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?php if($model->deletable) echo Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->pagomiscuentas_file_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
            <?php if($model->status == PagomiscuentasFile::STATUS_DRAFT) {
                echo Html::a(Yii::t('app', 'Close'), ['close', 'id' => $model->pagomiscuentas_file_id], [
                    'class' => 'btn btn-warning',
                    'data' => [
                        'confirm' => Yii::t('pagomiscuentas', 'Are you sure you want to close this item?'),
                        'method' => 'post',
                    ],
                ]);
            }?>

        </p>
    </div>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'company.name',
            'date'
        ],
    ]) ?>

    <?php
    if ($model->status == PagomiscuentasFile::STATUS_CLOSED) {
        //Clientes con empres errónea
        if($dataProviderCustomers->count > 0){
            echo '<hr style="padding-top: 20px"><h3>'.Yii::t('app', 'Customers in wrong company').'</h3>';
            echo GridView::widget([
                'dataProvider' => $dataProviderCustomers,
                'columns' => [
                    [
                        'attribute' => 'customer',
                        'value' => function($model) {
                            return $model->customer->fullName;
                        }
                    ],
                    [
                        'label' => Yii::t('app','Company'),
                        'value' => function($model) {
                            return $model->customer->company->name;
                        }
                    ],
                    [
                        'class' => 'app\components\grid\ActionColumn',
                        'template' => '{update}',
                        'buttons' => [
                            'update' => function($url, $model, $key){
                                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['/sale/customer/update', 'id' => $model->customer_id], [
                                    'title' => Yii::t('yii', 'Update'),
                                    'class' => 'btn btn-primary',
                                ]);

                            },
                        ],
                    ],
                ],
            ]);
        }

        //Pagos generados por el archivo de importación
        echo '<hr style="padding-top: 20px"><h3>'.Yii::t('app', 'Payments generated by import file').'</h3>';
        echo GridView::widget([
            'dataProvider' => $dataProviderPayments,
            'columns' => [
                'date',
                [
                    'attribute' => 'customer',
                    'value' => function($model) {
                        return $model->customer->fullName;
                    }
                ],
                'amount:currency',
                [
                    'class' => 'app\components\grid\ActionColumn',
                    'template' => '{view}',
                    'buttons' => [
                        'view' => function($url, $model, $key){
                            return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['/checkout/payment/view', 'id' => $model->payment_id], [
                                'title' => Yii::t('yii', 'Update'),
                                'class' => 'btn btn-view',
                            ]);

                        },
                    ],
                ],
            ],
        ]);

    }
    ?>
</div>
