version: '2'
services:
    rex-web:
        container_name: rex-web
        build: web-server
        volumes:
            - ../.:/var/www/html
        ports:
            - "8180:80"
            - "8181:443"
        networks:
            - docker-net

    rex-data:
        container_name: rex-data
        image: mariadb:10.0
        volumes:
            - ../_volumen_data:/var/lib/mysql
        ports:
            - "8183:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
        command: mysqld --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        networks:
            - docker-net

    rex-myadmin:
        container_name: rex-myadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8182:80"
        environment:
            PMA_HOST: 'rex-data'
            PMA_USER: 'root'
            PMA_PASSWORD: 'secret'
        networks:
            - docker-net

#    pdf-service:
#        container_name: pdf-service
#        build: pdf-service
#        ports:
#            - "5001:5001"
#        restart: always

networks:
    docker-net:
        driver: bridge


    #rex-selenium:
    #    image: selenium/standalone-chrome
    #    container_name: rex-selenium
    #    ports:
    #        - "8184:4444"
    #        - "8189:5900"
    #    links:
    #        - rex-web
