<?php

namespace app\modules\mobileapp\v1\models;

use app\modules\config\models\Config;
use app\modules\mailing\components\sender\MailSender;
use app\modules\mailing\models\EmailTransport;
use app\modules\sale\models\Company;
use Yii;
use app\modules\westnet\notifications\components\transports\IntegratechService;

/**
 * This is the model class for table "validation_code".
 *
 * @property integer $validation_code_id
 * @property string $code
 * @property integer $expire_timestamp
 * @property integer $user_app_has_customer_id
 *
 * @property UserAppHasCustomer $userAppHasCustomer
 */
class ValidationCode extends \app\components\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'validation_code';
    }
    

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_app_has_customer_id'], 'required'],
            [['validation_code_id', 'expire_timestamp', 'user_app_has_customer_id'], 'integer'],
            [['code'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'validation_code_id' => 'Validation Code ID',
            'code' => 'Code',
            'expire_timestamp' => 'Expire Timestamp',
            'user_app_has_customer_id' => 'User App Has Customer ID',
        ];
    }    


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserAppHasCustomer()
    {
        return $this->hasOne(UserAppHasCustomer::className(), ['user_app_has_customer_id' => 'user_app_has_customer_id']);
    }
         
    /**
     * @inheritdoc
     * Strong relations: None.
     */
    public function getDeletable()
    {
        return true;
    }
    
    /**
     * @brief Deletes weak relations for this model on delete
     * Weak relations: UserAppHasCustomer.
     */
    protected function unlinkWeakRelations(){
    }
    
    /**
     * @inheritdoc
     */
    public function beforeDelete()
    {
        if (parent::beforeDelete()) {
            if($this->getDeletable()){
                $this->unlinkWeakRelations();
                return true;
            }
        } else {
            return false;
        }
    }

    public function beforeSave($insert)
    {

        $this->expire_timestamp = time() + (60 * Config::getValue('validation_code_expire'));

        $digits = 4;
        $this->code = rand(pow(10, $digits-1), pow(10, $digits)-1);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function sendCodeSms($destinatary){
        $response = IntegratechService::sendSMS($destinatary, str_replace('{code}', $this->code, Config::getValue('sms_validation_content')));

        if($response['status'] == 'success'){
            return true;
        }
        return false;
    }

    public function sendEmail(){
        $company = Company::findOne(['name' => 'Westnet']);
        $sender = MailSender::getInstance('CODIGO_VALIDACION_EN_APP', Company::class, $company->company_id );

        return $sender->send($this->userAppHasCustomer->userApp->email,
            'Westnet App - Código de Validación de Registro',
            [
                'params' => [
                    'code' => $this->code,
                    'image' => $company->getLogoWebPath(),
                ]
            ]);
    }

}
