#!/bin/sh
./yii migrate --migrationPath=vendor/webimark/module-user-management/migrations --interactive=0
./yii migrate --migrationPath=modules/mailing/migrations --interactive=0
./yii migrate --migrationPath=modules/agenda/migrations --interactive=0
./yii migrate --migrationPath=modules/partner/migrations --interactive=0
./yii migrate --migrationPath=modules/sale/migrations --interactive=0
./yii migrate --migrationPath=modules/pagomiscuentas/migrations --interactive=0
./yii migrate --migrationPath=modules/config/migrations --interactive=0
./yii migrate --migrationPath=modules/westnet/migrations --interactive=0
./yii migrate --migrationPath=modules/westnet/ecopagos/migrations --interactive=0
./yii migrate --migrationPath=modules/westnet/notifications/migrations --interactive=0
./yii migrate --migrationPath=modules/westnet/reports/migrations
./yii migrate --migrationPath=modules/afip/migrations
./yii migrate --migrationPath=modules/mobileapp/migrations
./yii migrate --migrationPath=modules/log/migrations
./yii migrate --interactive=0
./yii migrate --migrationPath=vendor/conquer/oauth2/src/migrations
./yii migrate --migrationPath=modules/ivr/v1/migrations