#!/bin/bash

# Checking docker installed
command -v docker >/dev/null 2>&1 || { echo >&2 "Docker required but it's not installed. Aborting."; exit 1; }
command -v docker-compose >/dev/null 2>&1 || { echo >&2 "Docker required but it's not installed. Aborting."; exit 1; }

#docker-compose -f docker/docker-compose.yml build
echo ""
echo "$(tput setaf 3)Starting docker containers...$(tput sgr 0)"
echo ""
docker-compose -f docker/docker-compose.yml up -d
echo ""
echo "$(tput setaf 3)Waiting db engine to warm up...$(tput sgr 0)"

# check for a connection to the database server
check=$(wget -O - -T 2 "http://localhost:8183" 2>&1 | grep -o mysql)
while [ -z "$check" ]; do
    echo "Not yet..."
    sleep 5s
    check=$(wget -O - -T 2 "http://localhost:8183" 2>&1 | grep -o mysql)
done
echo "$(tput setaf 3)... ready.$(tput sgr 0)"
echo ""
echo "$(tput setaf 3)Waiting selenium engine to warm up...$(tput sgr 0)"

# check for a connection to selenium server
check=$(wget -O - -T 2 "http://localhost:8184" 2>&1 | grep -o Selenium)
while [ -z "$check" ]; do
    echo "Not yet..."
    sleep 5s
    check=$(wget -O - -T 2 "http://localhost:8184" 2>&1 | grep -o Selenium)
done
echo "$(tput setaf 3)... ready.$(tput sgr 0)"
echo ""
echo "$(tput setaf 3)Running tests...$(tput sgr 0)"
echo ""
docker exec -ti westnet-web vendor/bin/codecept run --html
echo ""
#echo "$(tput setaf 3)Releasing docker containers...$(tput sgr 0)"
echo ""
#docker-compose -f docker/docker-compose.yml down
echo ""
echo "$(tput setaf 3)Report available in $(tput bold)file://$(pwd)/tests/_logs/report.html$(tput sgr 0)"
echo ""
