<?php

use yii\db\Migration;

class m180514_134030_one_signal_params extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function safeUp()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Mobile App']);

        $this->insert("item", [
            'attr' => 'one_signal_app_id',
            'type' => 'textInput',
            'label' => 'App ID de One Signal',
            'description' => '',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => '3222eb5d-9c88-41c5-b3c4-053bf2671228'
        ]);

        $this->insert("item", [
            'attr' => 'one_signal_rest_key',
            'type' => 'textInput',
            'label' => 'Rest Api Key de One Signal',
            'description' => '',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => 'ZTg3MWE3OTktNjY4ZC00YWQ2LTgyMDUtZjBhNDIyYjNlYmMy'
        ]);
    }

    public function safeDown()
    {
        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
