<?php

use yii\db\Migration;

class m180507_150244_validation_code_expire_param extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function safeUp()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Mobile App']);

        if (empty($category)){
            $category= new \app\modules\config\models\Category(['name' => 'Mobile App', 'status' => 'enabled']);
            $category->save();
        }

        $this->insert("item", [
            'attr' => 'validation_code_expire',
            'type' => 'textInput',
            'label' => 'Duración del código de validación',
            'description' => 'Tiempo de duracion en minutos del código de validación de los usuarios de la app',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => '10'
        ]);
    }

    public function safeDown()
    {
        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
