<?php

use yii\db\Migration;

class m180514_180410_mobile_push_transport_create extends Migration
{
    public function init()
    {
        $this->db= 'dbnotifications';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $this->insert('transport', [
            'name' => 'Mobile Push',
            'slug' => 'mobile-push',
            'class' => \app\modules\westnet\notifications\components\transports\MobilePushTransport::className(),
        ]);
    }

    public function down()
    {
        $this->delete('transport', ['slug' => 'mobile-push']);
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
