<?php

use yii\db\Migration;

class m180517_143223_sms_api_params extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Mobile App']);

        $this->insert("item", [
            'attr' => 'sms_api_username',
            'type' => 'textInput',
            'label' => 'Usuario Api SMS',
            'description' => '',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => 'quoma'
        ]);

        $this->insert("item", [
            'attr' => 'sms_api_password',
            'type' => 'textInput',
            'label' => 'Password Api SMS',
            'description' => '',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => 'quoma2018'
        ]);

        $this->insert("item", [
            'attr' => 'sms_api_url',
            'type' => 'textInput',
            'label' => 'Url Api SMS',
            'description' => 'Url al endpoint de la api para enviar sms.',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => 'http://207.38.89.147:8443/bin/send.json'
        ]);
    }

    public function safeDown()
    {
        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
