<?php

use yii\db\Migration;

class m180504_200347_mobile_app_private_token_param extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function safeUp()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Mobile App']);

        if (empty($category)){
            $category= new \app\modules\config\models\Category(['name' => 'Mobile App', 'status' => 'enabled']);
            $category->save();
        }

        $this->insert("item", [
            'attr' => 'private_token',
            'type' => 'textInput',
            'label' => 'Token para peticiones a la Api de mobile app',
            'description' => '',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => '123456'
        ]);
    }

    public function safeDown()
    {
        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
