<?php

use yii\db\Migration;

class m180514_214025_invoice_mobile_push_content_param extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Mobile App']);

        $this->insert("item", [
            'attr' => 'invoice_mobile_push_content',
            'type' => 'textInput',
            'label' => 'Texto para notificación al facturar',
            'description' => 'Texto que se mostrara en la notificación de la app cuando se genere una factura',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => 'Su nueva factura ya está disponible'
        ]);
    }

    public function down()
    {
        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
