<?php

use yii\db\Migration;

class m180522_194750_ecopagos_company_param extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function safeUp()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Mobile App']);

        $this->insert("item", [
            'attr' => 'ecopagos_company_id',
            'type' => 'textInput',
            'label' => 'ID Company con ecopagos',
            'description' => 'ID de la empresa que usa los ecopagos',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => 0
        ]);
    }

    public function safeDown()
    {
        return true;
    }
    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
