<?php

use yii\db\Migration;

class m180517_184555_sms_validation_content extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function safeUp()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Mobile App']);

        $this->insert("item", [
            'attr' => 'sms_validation_content',
            'type' => 'textInput',
            'label' => 'Contenido de SMS de validación',
            'description' => 'El contenido deberá tener la referencia "{code}" en el lugar donde debe ir el código',
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 1,
            'default' => 'Gracias por registrarse en nuestra app. Su código de validación es: {code}'
        ]);
    }

    public function safeDown()
    {
        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
