<?php

use app\modules\config\models\Category;
use yii\db\Migration;

/**
 * Class m190801_163248_direct_debit_default_concept
 */
class m190801_163248_direct_debit_default_concept extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $category = Category::findOne(['name' => 'Comprobantes']);
//
        $this->insert('item', [
            'attr' => 'direct_debit_default_concept',
            'type' => 'textInput',
            'label' =>"Concepto por defecto para Débito Directo",
            'description' => "",
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 0,
            'default' => 'Westnet'
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $item = \app\modules\config\models\Item::findOne(['attr' => 'direct_debit_default_concept']);

        if ($item) {
            $item->delete();
        }
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190801_163248_direct_debit_default_concept cannot be reverted.\n";

        return false;
    }
    */
}
