<?php

use yii\db\Migration;

/**
 * Class m190611_163615_limit_sms_per_month_per_customer
 */
class m190611_163615_limit_sms_per_month_per_customer extends Migration
{

    public function init()
    {
        $this->db = 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Customer']);

        if (empty($category)) {
            $category = new \app\modules\sale\models\Category(['name' => 'Customer', 'status' => 'enabled']);

            $category->save();
        }

        $this->insert('item', [
            'attr' => 'sms_per_customer',
            'type' => 'textInput',
            'label' =>"Cantidad de SMS al mes por Cliente",
            'description' => "Cantidad de SMS al mes que se le puede enviar al Cliente. No incluye campañas masivas",
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 0,
            'default' => '2'
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $item = \app\modules\config\models\Item::findOne(['attr' => 'sms_per_customer',]);

        if ($item) {
            $item->delete();
        }
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190611_163615_limit_sms_per_month_per_customer cannot be reverted.\n";

        return false;
    }
    */
}
