<?php

use yii\db\Migration;

/**
 * Class m190315_182126_categoria_de_cobranza_param
 */
class m190315_182126_categoria_de_cobranza_param extends Migration
{

    public function init()
    {
        $this->db = 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $category = \app\modules\config\models\Category::findOne(['name' => 'Ticket']);

        if (empty($category)) {
            $category = new \app\modules\config\models\Category(['name' => 'Ticket', 'status' => 'enabled']);

            $category->save();
        }

        $collectionCategory = \app\modules\ticket\models\Category::findOne(['slug' => 'gestion-de-cobranza']);

        $this->insert('item', [
            'attr' => 'cobranza_category_id',
            'type' => 'textInput',
            'label' =>"Categoria de Cobranzas",
            'description' => "Indica la categoria de tickets de cobranza",
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 0,
            'default' => ($collectionCategory ? $collectionCategory->category_id : 0)
        ]);


    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $item = \app\modules\config\models\Item::findOne(['attr' => 'cobranza_category_id']);

        if ($item && $item->delete()) {
            return true;
        }

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190315_182126_categoria_de_cobranza_param cannot be reverted.\n";

        return false;
    }
    */
}
