<?php

use yii\db\Migration;

/**
 * Class m190813_202215_ticket_status_cerrado_por_jefe_cobranza
 */
class m190813_202215_ticket_status_cerrado_por_jefe_cobranza extends Migration
{
    public function init()
    {
        $this->db = 'dbticket';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->insert('status', [
            'name' => 'Cerrado (Por Jefe de Cobranza)',
            'description' => 'Tickets cerrados por el jefe de cobranza',
            'is_open' => false,
        ]);

        $status_id = $this->db->lastInsertID;

        $schema = \app\modules\ticket\models\Schema::findOne(['name' => 'Cobranza']);

        if (empty($schema)) {
            return false;
        }

        $this->insert('schema_has_status', [
            'schema_id' => $schema->schema_id,
            'status_id' => $status_id
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $status = \app\modules\ticket\models\Status::findOne(['name' => 'Cerrado (Por Jefe de Cobranza)']);

        if (empty($status)) {
            return true;
        }

        $this->delete('schemas_has_status', ['status_id' => $status->status_id]);
        $status->delete();
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190813_202215_ticket_status_cerrado_por_jefe_cobranza cannot be reverted.\n";

        return false;
    }
    */
}
