<?php

use app\modules\config\models\Category;
use yii\db\Migration;

/**
 * Class m190702_194830_debt_bills_count_to_force_param
 */
class m190702_194830_debt_bills_count_to_force_param extends Migration
{
    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $category = Category::findOne(['name' => 'Mobile App']);
//
        $this->insert('item', [
            'attr' => 'payment_extension_debt_bills',
            'type' => 'textInput',
            'label' =>"Cantidad de Facturas adeudadas para solicitar extensión de pago",
            'description' => "Indica la cantidad de facturas adeudadas máxima para solicitar extensión de pago",
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 0,
            'default' => 2
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {

    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190702_194830_debt_bills_count_to_force_param cannot be reverted.\n";

        return false;
    }
    */
}
