<?php

use yii\db\Migration;

/**
 * Class m190315_183603_categoria_de_cobranza
 */

use app\modules\ticket\models\Category;

class m190315_182100_categoria_de_cobranza extends Migration
{

    public function init()
    {
        $this->db = 'dbticket';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $administracion_category = $this->db->createCommand("SELECT category_id, parent_id, lft, rgt FROM category where slug = 'Administración'")->queryOne();

        if (!empty($administracion_category)){
            $lastchildresult= $this->db->createCommand("SELECT * from category where parent_id = ':parent' ORDER BY category_id DESC", ['parent' => $administracion_category['category_id']])->queryOne();

            if (!empty($lastchildresult)) {
                $rgt = $lastchildresult['rgt'];
            }else {
                $rgt = $administracion_category['lft'];
            }

            $this->db->createCommand('UPDATE category SET rgt = rgt+2 WHERE rgt > ' . $rgt)->execute();
            $this->db->createCommand('UPDATE category SET lft = lft+2 WHERE lft > ' . $rgt)->execute();

            $this->insert('category', [
                'name' => 'Gestión de Cobranza',
                'description' => 'Ticket de cobranza',
                'parent_id' => $administracion_category['category_id'],
                'notify' => 0,
                'slug' => 'gestion-de-cobranza',
                'lft' => $rgt + 1,
                'rgt' => $rgt + 2,
            ]);

            return true;
        }

        return false;

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $category= Category::findOne(['gestion-de-cobranza']);

        if ($category && $category->delete()) {
            return true;
        }

        return false;
    }
}
