<?php

use yii\db\Migration;

/**
 * Class m190524_203407_infobip_transport
 */
class m190524_203407_infobip_transport extends Migration
{
    public function init()
    {
        $this->db = 'dbnotifications';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->insert('transport', [
           'name' => 'SMS Infobip',
           'slug' => 'sms-infobip',
           'class' => 'app\modules\westnet\notifications\components\transports\SMSInfobipTransport',
           'description' => 'Servicio de Infobip para SMS'
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $transport = \app\modules\westnet\notifications\models\Transport::findOne(['slug' => 'sms-infobip']);

        $transport->delete();
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190524_203407_infobip_transport cannot be reverted.\n";

        return false;
    }
    */
}
