<?php

use app\modules\config\models\Category;
use yii\db\Migration;

/**
 * Class m190801_143234_leyenda_debito_directo
 */
class m190801_143234_leyenda_debito_directo extends Migration
{

    public function init()
    {
        $this->db= 'dbconfig';
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $category = Category::findOne(['name' => 'Comprobantes']);
//
        $this->insert('item', [
            'attr' => 'direct_debit_bill_text',
            'type' => 'textInput',
            'label' =>"Leyenda de Debito Directo en Factura",
            'description' => "Leyenda que aparecera en la factura si el cliente esta adherido al debito directo",
            'multiple' => 0,
            'category_id' => $category->category_id,
            'superadmin' => 0,
            'default' => 'El monto de esta factura se debitará de su cuenta bancaria'
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $item = \app\modules\config\models\Item::findOne(['attr' => 'direct_debit_bill_text']);

        if ($item) {
            $item->delete();
        }
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m190801_143234_leyenda_debito_directo cannot be reverted.\n";

        return false;
    }
    */
}
