<?php

use yii\db\Migration;

/**
 * Class m191025_205417_user_close_column_in_ticket
 */
class m191025_205417_user_close_column_in_ticket extends Migration
{
    public function init()
    {
        $this->db = 'dbticket';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->addColumn('ticket', 'closed_by', 'INT NULL');
        $this->addColumn('ticket', 'closed_timestamp', 'INT NULL');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropColumn('ticket', 'closed_by' );
        $this->dropColumn('ticket', 'closed_timestamp');
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m191025_205417_user_close_column_in_ticket cannot be reverted.\n";

        return false;
    }
    */
}
