<?php

use yii\db\Migration;

/**
 * Class m191210_143640_customer_installed_app_filter_destinatary
 */
class m191210_143640_customer_installed_app_filter_destinatary extends Migration
{
    public function init()
    {
        $this->db = 'dbnotifications';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->addColumn('destinatary', 'has_app', 'VARCHAR(45) NULL');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropColumn('destinatary', 'has_app');
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m191210_143640_customer_installed_app_filter_destinatary cannot be reverted.\n";

        return false;
    }
    */
}
