<?php

namespace app\modules\ivr\v1\controllers;

use app\modules\ivr\v1\components\Controller;
use Yii;
use yii\base\Exception;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use app\modules\sale\models\Customer;
use app\modules\westnet\models\EmptyAds;

/**
 * ContractController implements the CRUD actions for Contract model.
 */
class ContractController extends Controller
{

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'verbFilter' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'search' => ['POST']
                ],
            ],
        ]); // TODO: Change the autogenerated stub
    }

    //copia de modules/sale/modules/contract/views/contract/active-contract.php
    /* public function actionActiveContract($id) {
        $model = $this->findModel($id);
        $connection = Connection::findOne(['contract_id' => $model->contract_id]);
        
        if (!$connection) {
            $connection = new Connection();
        }

        $nodesQuery = Node::find();
        $nodesQuery->select(['node.node_id', 'concat(node.name, \' - \', s.name) as name'])
            ->leftJoin('server s', 'node.server_id = s.server_id')
            ->orderBy('node.name');
            

        $nodes = ArrayHelper::map($nodesQuery->all(), 'node_id', 'name');
        
        if (!empty($_POST['Contract']) && $_POST['Contract']['customerCodeADS'] !== '') {
            $code = $_POST['Contract']['customerCodeADS'];
            $customer = Customer::findOne(['customer_id' => $model->customer_id]);
            // Busco el ADS vacio
            $emptyAds = EmptyAds::findOne(['code' => $code , 'used' => false]);
            // Si tiene ADS vacio, tengo que forzar la actualizacion del company en el cliente.
            if(!empty($emptyAds)) {
                $customer->code = $code;
                $customer->payment_code = $emptyAds->payment_code;
                $customer->company_id = $emptyAds->company_id;
                $customer->status = Customer::STATUS_ENABLED;
                $emptyAds->used = true;
                $customer->save(false);
                $emptyAds->updateAttributes(['used']);
            }else{
                Yii::$app->session->setFlash('error', Yii::t('app', 'This ADS has been used before or not exist'));
                return $this->render('active-contract', [
                    'model' => $model,
                    'connection' => $connection,
                    'action' => 'active',
                    'nodes' => $nodes
                ]);
            }
        }

        $model->from_date = Yii::$app->formatter->asDate(new DateTime());
        $model->setScenario('invoice');
        if ($model->load(Yii::$app->request->post()) && $connection->load(Yii::$app->request->post()) && $model->validate()) {
            $connection->contract_id = $model->contract_id;
            $connection->due_date = null;

            // Si viene desde un vendedor, no va a tener empresa, por lo que hay que sacarla de del nodo.
            //Si la coneccion se guarda
            if ($connection->save() && $model->save()) {
                $cti = new ContractToInvoice();
                if ($cti->createContract($model, $connection)) {
                    $model->customer->sendMobileAppLinkSMSMessage();
                    Ticket::createGestionADSTicket($model->customer_id);
                    $model->customer->updateAttributes(['status' => Customer::STATUS_ENABLED]);
                    return $this->redirect(['/sale/contract/contract/view', 'id' => $model->contract_id]);
                }
            }
        }

        return $this->render('active-contract', [
                    'model' => $model,
                    'connection' => $connection,
                    'action' => 'active',
                    'nodes' => $nodes
        ]);
    } */

    /**
     * Activa contrato a traves de API (necesita auth token)
     *
     * @return json
     */
    public function actionCreateContract()
    {
        $post = Yii::$app->request->post();
        $msg = "msg:: ";

        // if all post data is valid, activate a new contract
        if (isset($post['node_id']) && isset($post['customer_id'])  && isset($post['ads_code'])) {
            
            $model = $this->findModel($id);

            $msg .= " node_id : ".$post['node_id'];
            $msg .= " customer_id : ".$post['customer_id'];
            $msg .= " ads_code : ".$post['ads_code'];

            $code = $post['ads_code'];
            $customer = Customer::findOne(['customer_id' => $model->customer_id]);
            // search for empty ADS code number
            $emptyAds = EmptyAds::findOne(['code' => $code , 'used' => false]);
            
            // if the ADS number is empty, update the customer data
            if(!empty($emptyAds)) {
               /*  $customer->code = $code;
                $customer->payment_code = $emptyAds->payment_code;
                $customer->company_id = $emptyAds->company_id;
                $customer->status = Customer::STATUS_ENABLED;
                $emptyAds->used = true;
                $customer->save(false);
                $emptyAds->updateAttributes(['used']); */
                
                $msg .= " ADS is empty";

            }



        }


        return array(
            'status' => true,
            'msg' => $msg,
        );


        $err = "Invalid data.";
        return array(
            'status' => false,
            'error' => $err,
        );
    }
}
