<?php
/**
 * Created by PhpStorm.
 * User: juan
 * Date: 16/07/19
 * Time: 13:14
 */

namespace app\modules\ivr\v1\controllers;


use app\modules\ivr\v1\components\Controller;
use app\modules\ivr\v1\models\search\CustomerSearch;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;

class CustomerController extends Controller
{


    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'verbFilter' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'search' => ['POST']
                ],
            ],
        ]); // TODO: Change the autogenerated stub
    }

    public function actionSearch()
    {

        $data = \Yii::$app->request->post();

        if (empty($data['field']) && empty($data['value']) ) {
            \Yii::$app->response->setStatusCode(400);
            return [
                'error' => \Yii::t('ivrapi','"field" and "value" params are required')
            ];
        }


        if (empty($data['field'])) {
            \Yii::$app->response->setStatusCode(400);
            return [
                'error' => \Yii::t('ivrapi','"field" param is required')
            ];
        }

        if (empty($data['value'])) {
            \Yii::$app->response->setStatusCode(400);
            return [
                'error' => \Yii::t('ivrapi','"value" param is required')
            ];
        }

        $search = new CustomerSearch();
        $dataProvider = new ActiveDataProvider(['query' => $search->search($data)]);

        if ($dataProvider->count === 0 ) {
            \Yii::$app->response->setStatusCode(400);
            return  [
                'error' => \Yii::t('ivrapi','Customer not found')
            ];
        }

        return $dataProvider;

    }
}