<?php
/**
 * Created by PhpStorm.
 * User: juan
 * Date: 17/07/19
 * Time: 11:07
 */

namespace app\modules\ivr\v1\controllers;


use app\modules\ivr\v1\components\Controller;
use app\modules\ivr\v1\models\search\PaymentMethodSearch;
use yii\filters\VerbFilter;

class InfoController extends Controller
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'verbFilter' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'payment-methods' => ['GET']
                ],
            ],
        ]); // TODO: Change the autogenerated stub
    }


    /**
     * @SWG\Get(path="/info/payment-methods",
     *     tags={"Info"},
     *     summary="",
     *     description="(D-2) Devuelve un array con los metodos de pagos habilitados",
     *     produces={"application/json"},
     *     security={{"auth":{}}},
     *
     *     @SWG\Response(
     *         response = 200,
     *         description = "Devuelve un array con los metodos de pagos habilitados",
     *          @SWG\Schema(ref="#/definitions/PaymentMethod"),
     *     ),
     *     @SWG\Response(
     *         response = 401,
     *         description = "No Autorizado",
     *         @SWG\Schema(ref="#/definitions/Error2"),
     *     ),
     *
     * )
     *
     */
    public function actionPaymentMethods()
    {
        $search= new PaymentMethodSearch();

        return [
            'error' => 'false',
            'data' => $search->search()->getModels(),
        ];
    }


}