<?php
/**
 * Created by PhpStorm.
 * User: juan
 * Date: 17/07/19
 * Time: 11:07
 */

namespace app\modules\ivr\v1\controllers;


use app\modules\ivr\v1\components\Controller;
use yii\filters\VerbFilter;

class InfoController extends Controller
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'verbFilter' => [
                'class' => VerbFilter::class,
                'actions' => [
                    //'search' => ['POST']
                ],
            ],
        ]); // TODO: Change the autogenerated stub
    }



}