<?php
namespace app\modules\ivr\v1\controllers;


use Yii;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use app\modules\ivr\v1\components\Controller;
use app\modules\westnet\notifications\models\SiroPaymentIntentionValoration;

class PaymentIntentionController extends Controller
{
	public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'verbFilter' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'search' => ['POST']
                ],
            ],
        ]); // TODO: Change the autogenerated stub
    }

    public function actionSearchPaymentIntention(){
    	$data = Yii::$app->request->post();
    	$result = SiroPaymentIntentionValoration::findModel($data['siro_payment_intention_id']);

    	if(!empty($result))
    	    return  ['error' => false,
                     'data' => $result
                    ];
        else
        	return  ['error' => true,
                     'data' => null
                    ];
    }

    public function actionCreateValoration(){
        $data = Yii::$app->request->post();
        $model = new SiroPaymentIntentionValoration();

        $model->name = $data['name'];
        $model->email = $data['email'];
        $model->description = $data['description'];
        $model->siro_payment_intention_id = $data['siro_payment_intention_id'];
        $model->created_at = date('Y-m-d H:m:s');
        
        return $model->save(false);
    }

}