<?php 
namespace app\modules\ivr\v1\controllers;

use app\modules\config\models\Config;
use app\modules\ivr\v1\components\Controller;

use Yii;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;

class QuotaController extends Controller
{
	public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'verbFilter' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'search' => ['POST']
                ],
            ],
        ]); // TODO: Change the autogenerated stub
    }

    public function actionNodes(){
    	$nodes = Yii::$app->db->createCommand('SELECT node_id, no.name AS node_name, no.status AS node_status, se.server_id, se.name AS server_name, se.status AS server_status , url, subnet, vlan, geocode FROM node no LEFT JOIN server se ON se.server_id = no.server_id')->queryAll();

    	return [
    		'error' => false,
    		'data' => $nodes
    	];
    }

   public function actionGetCustomerCode($code){
        $nodes = Yii::$app->db->createCommand('SELECT * FROM customer WHERE code = :code')->bindValue('code',$code)->queryAll();

        return [
                'error' => false,
                'data' => $nodes
        ];
    }


}
