version: '2'
services:
    westnet-web:
        container_name: westnet-web
        build: web-server
        volumes:
            - ../.:/var/www/html
        ports:
            - "8180:80"
            - "8181:443"
        networks:
            - docker-net

    westnet-data:
        container_name: westnet-data
        image: mariadb:10.0
        volumes:
            - /home/ram/westnet:/var/lib/mysql
        ports:
            - "8183:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
        networks:
            - docker-net

    westnet-myadmin:
        container_name: westnet-myadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8182:80"
        environment:
            PMA_HOST: 'westnet-data'
            PMA_USER: 'root'
            PMA_PASSWORD: 'secret'
        networks:
            - docker-net

    westnet-pdf:
        container_name: westnet-pdf
        build: pdf-service
        ports:
            - "8184:5001"
        networks:
            - docker-net

networks:
    docker-net:
        driver: bridge
            



    #westnet-selenium:
    #    image: selenium/standalone-chrome
    #    container_name: westnet-selenium
    #    ports:
    #        - "8184:4444"
    #        - "8189:5900"
    #    links:
    #        - westnet-web
