version: '2'
services:
    rex-web:
        container_name: rex-web
        build: web-server
        volumes:
            - ../.:/var/www/html
        ports:
            - "8180:80"
            - "8181:443"
        networks:
            - docker-net

    rex-data:
        container_name: rex-data
        image: mariadb:10.0
        volumes:
            - /home/ram/rex:/var/lib/mysql
        ports:
            - "8183:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
        networks:
            - docker-net

    rex-myadmin:
        container_name: rex-myadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8182:80"
        environment:
            PMA_HOST: 'rex-data'
            PMA_USER: 'root'
            PMA_PASSWORD: 'secret'
        networks:
            - docker-net

    #rex-pdf:
     #   container_name: rex-pdf
      #  build: pdf-service
       # ports:
        #    - "8184:5001"
       # networks:
        #    - docker-net

networks:
    docker-net:
        driver: bridge
            



    #rex-selenium:
    #    image: selenium/standalone-chrome
    #    container_name: rex-selenium
    #    ports:
    #        - "8184:4444"
    #        - "8189:5900"
    #    links:
    #        - rex-web
