<?php
/**
 * Created by PhpStorm.
 * User: juan
 * Date: 16/07/19
 * Time: 13:24
 */

namespace app\modules\ivr\v1\models;



class Customer extends \app\modules\sale\models\Customer
{

    public function fields()
    {
        return [
            'customer_id',
            'fullName',
            'documentType',
            'document_number',
            'code'
        ]; // TODO: Change the autogenerated stub
    }

    public function accountInfo() {
        $data = [];

        $current_balance = $this->current_account_balance;

        $lastPayment = Payment::find()->andWhere(['customer_id' => $this->customer_id])->orderBy(['timestamp' => SORT_DESC])->one();

        $data['balance'] = ($current_balance !== null ? $current_balance : 0);

        if($lastPayment) {
            $data['last_payment'] = $lastPayment;
        }

        return $data;
    }

}