<?php
/**
 * Created by PhpStorm.
 * User: juan
 * Date: 19/07/19
 * Time: 15:07
 */

namespace app\modules\ivr\v1\models;


class Payment extends \app\modules\checkout\models\Payment
{
    public function fields()
    {
        return [
            'amount',
            'date' => function ($model) {
                return date('d-m-Y', $model->timestamp);
            }
        ]; // TODO: Change the autogenerated stub
    }
}