version: '2'
services:

    pdf-service:
        container_name: pdf-service
        build: pdf-service
        ports:
            - "5001:5001"
        restart: always

networks:
    docker-net:
        driver: bridge

