<?php
/**
 * Created by PhpStorm.
 * User: quoma
 * Date: 27/03/19
 * Time: 11:16
 */

namespace app\modules\sale\models;
use app\components\db\ActiveRecord;

/**
 * @property integer $chcm_id
 * @property integer $customer_id
 * @property integer $customer_message_id
 * @property integer $timestamp
 *
 * @property Customer $customer
 * @property CustomerMessage $customerMessage
 */
class CustomerHasCustomerMessage extends ActiveRecord
{
    public static function tableName()
    {
        return 'customer_has_customer_message'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['customer_id', 'customer_message_id', 'timestamp'], 'required'],
            [['chcm_id','customer_id', 'customer_message_id', 'timestamp'], 'integer']
        ];
    }

    public function attributeLabels()
    {
        return [
            'customer_id' => Yii::t('app','Customer'),
            'customer_message_id' => Yii::t('app','Customer Message'),
            'timestamp' => Yii::t('app','Date and Time')
        ];
    }

    public function getCustomer()
    {
        return $this->hasOne(Customer::class, ['customer_id' => 'customer_id']);
    }

    public function getCustomerMessage()
    {
        return $this->hasOne(CustomerMessage::class, ['customer_message_id' => 'customer_message_id']);
    }


}