<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Activo',
    'Are you sure you want to delete this user?' => '¿Deseas eliminar este usuario?',
    'Bind to IP' => 'Asignar IP',
    'Browser' => 'Navegador',
    'Change own password' => 'Cambiar mi clave',
    'Change password' => 'Cambiar clave',
    'Changing password' => 'Cambiando clave',
    'Changing password for user: ' => 'Cambiando clave para usuario',
    'Child permissions' => 'Permisos hijos',
    'Child roles' => 'Roles hijos',
    'Code' => 'Código',
    'Create' => 'Alta',
    'Created' => 'Creado',
    'Creating permission group' => 'Creando grupo de permisos',
    'Current password' => 'Clave actual',
    'Data' => 'Datos',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'E-mail confirmed' => 'Email confirmado',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' 
        => 'Se ha enviado un correo con un link de activación al correo <strong>{email}</strong>. Este link expirará en {minutes} minutos.',
    'Edit' => 'Editar',
    'Editing' => 'Editando',
    'Editing permission group' => 'Editando grupo de permisos',
    'Editing permission: ' => 'Editando permiso: ',
    'Editing role: ' => 'Editando rol: ',
    'Editing user: ' => 'Editando usuario: ',
    'For example: 123.34.56.78, 168.111.192.12' => 'Por ejemplo: 123.34.56.78, 168.111.192.12',
    'Group' => 'Grupo',
    'Inactive' => 'Inactivo',
    'Language' => 'Lenguaje',
    'Login' => 'Login',
    'Name' => 'Nombre',
    'OS' => 'Sistema operativo',
    'Password' => 'Clave',
    'Password has been changed' => 'La clave ha sido modificada',
    'Permission creation' => 'Alta de permiso',
    'Permission groups' => 'Grupos',
    'Permissions' => 'Permisos',
    'Permissions for role - "{role}"' => 'Permisos para rol "{role}"',
    'Permissions for role:' => 'Permisos para rol: ',
    'Registration IP' => 'Ip de registro',
    'Repeat password' => 'Repetir clave',
    'Reset' => 'Reset',
    'Role creation' => 'Alta de rol',
    'Roles' => 'Roles',
    'Roles and permissions' => 'Roles y permisos',
    'Roles and permissions for user:' => 'Roles y permisos para usuario: ',
    'Rule' => 'Regla',
    'Save' => 'Guardar',
    'Saved' => 'Guardado',
    'Search' => 'Buscar',
    'Settings for permission' => 'Ajustes para el permiso',
    'Status' => 'Estado',
    'Superadmin' => 'Superadmin',
    'Too many attempts' => 'Demasiados intentos',
    'Type' => 'Tipo',
    'Updated' => 'Actualizado',
    'User' => 'Usuario',
    'User agent' => 'User agent',
    'User creation' => 'Alta de usuario',
    'Users' => 'Usuarios',
    'Visit Time' => 'Hora de acceso',
    'Visit log' => 'Log de acceso',
    'Wrong format. Enter valid IPs separated by comma' => 'Formato incorrecto. Ingrese IPs válidas separadas por coma.',
    'Wrong password' => 'Clave incorrecta',
    'You can not change own permissions' => 'No puedes cambiar tus permisos',
];