<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authorization' => 'Autorización',
    'Captcha' => 'Captcha',
    'Change own password' => 'Cambiar clave',
    'Check your E-mail for further instructions' => 'Revisa tu correo para más instrucciones.',
    'Check your e-mail {email} for instructions to activate account' 
        => 'Revisa tu correo {email}. Encontrarás instrucciones para la activación de tu cuenta.',
    'Confirm' => 'Confirmar',
    'Confirm E-mail' => 'Confirmar email',
    'E-mail confirmation' => 'Confirmar email',
    'Could not send confirmation email' => 'No se ha podido enviar el correo de confirmación',
    'E-mail confirmation for' => 'Correo de confirmación para ',
    'E-mail confirmed' => 'Email confirmado',
    'E-mail is invalid' => 'Email inválido',
    'Forgot password ?' => '¿Olvidaste tu clave?',
    'Incorrect username or password.' => 'Combinación de nombre de usuario y contraseña incorrecta.',
    'Login' => 'Login',
    'Login has been taken' => 'Estos datos de login ya han sido tomados por otro usuario.',
    'Password' => 'Clave',
    'Password recovery' => 'Recuperar clave',
    'Password reset for' => 'Reiniciar clave para ',
    'Recover' => 'Recuperar',
    'Register' => 'Registrar',
    'Registration' => 'Registro',
    'Registration - confirm your e-mail' => 'Registro - confirma tu email',
    'Remember me' => 'Recordarme',
    'Repeat password' => 'Repetir clave',
    'This E-mail already exists' => 'Este correo ya existe',
    'Token not found. It may be expired' => 'Token no encontrado. Quizás ya expiró.',
    'Token not found. It may be expired. Try reset password once more' 
        => 'Token no encontrado. Quizás ya expiró. Intenta volver a reiniciar la clave.',
    'Too many attempts' => 'Demasiados intentos',
    'Unable to send message for email provided' => 'No es posible enviar un correo para el email provisto.',
    'You could not login from this IP' => 'No puedes acceder desde esta IP.',
];